module.exports = {
  TEACHERS_AMOUNT: 3,
  STUDENTS_AMOUNT: 10,
  QUESTIONS_PER_STUDENT: 5,
  REPLIES_PER_QUESTION: 3,
  IMAGES_IN_QUESTIONS: 20,
  IMAGES_IN_REPLIES: 50,
  FOLLOWSHIP_AMOUNT: 50,
  LIKE_QUESTION_AMOUNT: 50,
  LIKE_REPLY_AMOUNT: 200
}
