module.exports = {
  TEACHERS_AMOUNT: 3,
  STUDENTS_AMOUNT: 10,
  QUESTIONS_PER_STUDENT: 5,
  REPLIES_PER_QUESTION: 3,
  STUDENT_FOLLOW_TEACHER_AMOUNT: 20,
  STUDENT_FOLLOW_STUDENT_AMOUNT: 20,
  LIKE_QUESTION_AMOUNT: 50,
  LIKE_REPLY_AMOUNT: 200
}
